name: Quality Template

runs:
  using: "composite"
  steps:
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
      shell: bash
      
    - name: Merge test results and generate report
      run: |
        reportgenerator -reports:coverage/**/coverage.cobertura.xml -targetdir:coverage/report -reporttypes:Html
      shell: bash