name: Publish Template

inputs:
  os:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Publish build artifacts
      run: dotnet publish --configuration Release --output ./artifacts
      shell: bash

    - name: Archive production artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact-${{ inputs.os }}
        path: ./artifacts