name: Test Template

runs:
  using: "composite"
  steps:
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
      shell: bash