name: CodeQL Analysis Template

runs:
  using: "composite"
  steps:
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: 'security'

#    - name: Write to Job Summary
#      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
#      shell: bash
#
#    - name: Add Coverage PR Comment
#      uses: marocchino/sticky-pull-request-comment@v2
#      if: github.event_name == 'pull_request'
#      with:
#        recreate: true
#        path: code-coverage-results.md