name: Mutation Template

runs:
  using: "composite"
  steps:
    - name: Download Stryker
      run: dotnet tool install -g dotnet-stryker
      shell: bash
    
    - name: Run Mutation Tests
      run: dotnet stryker
      shell: bash