name: Build Template

runs:
  using: "composite"
  steps:
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'csharp'
      
    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build project
      run: dotnet build --configuration Release --no-restore
      shell: bash