name: Build Template

inputs:
  os:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build project
      run: dotnet build --configuration Release --no-restore
      shell: bash