name: Publish Template

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Publish build artifacts
        run: dotnet publish --configuration Release --output ./artifacts

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-${{ inputs.os }}
          path: ./artifacts